--Remoção das tabelas
DROP TABLE FOTO CASCADE;
DROP TABLE IMMOBILIE CASCADE;
DROP TABLE MAKLERBUERO CASCADE;
DROP TABLE UMFASST CASCADE;
DROP TABLE STADTTEIL CASCADE;
DROP TABLE STADT CASCADE;
DROP TABLE BUNDESLAND CASCADE;

--Criação das tabelas
CREATE TABLE FOTO 
    ( 
     FTO_BILD CHARACTER VARYING (50) NOT NULL,
     FTO_NAME CHARACTER VARYING (100) NOT NULL, 
     FTO_IMM_ID INTEGER NOT NULL
    ) 
;

CREATE TABLE MAKLERBUERO 
    ( 
     MAK_CNPJ CHARACTER VARYING (50) NOT NULL,
     MAK_NAME CHARACTER VARYING (100) NOT NULL,
     MAK_TELEFONNUMMER1 CHARACTER VARYING (50),
     MAK_TELEFONNUMMER2 CHARACTER VARYING (50),
     MAK_TELEFONNUMMER3 CHARACTER VARYING (50),
     MAK_STRASSE CHARACTER VARYING (100),
     MAK_ANZAHL INTEGER,
     MAK_ERGARNZUNG CHARACTER VARYING (100),
     MAK_STL_ID INTEGER
    ) 
;

ALTER TABLE MAKLERBUERO 
    ADD CONSTRAINT MAKLERBUERO_PK PRIMARY KEY ( MAK_CNPJ ) ;

CREATE TABLE IMMOBILIE 
    ( 
     IMM_ID SERIAL,
     IMM_PREIS DOUBLE PRECISION NOT NULL,
     IMM_FLAECHE CHARACTER VARYING (50) NOT NULL,
     IMM_ZIMMERQUANTITAET INTEGER NOT NULL,
     IMM_EGR_PARKPLATZ BOOLEAN NOT NULL,
     IMM_SONNENSTUNDEN CHARACTER VARYING (20) NOT NULL,
     IMM_ADE_EINZELHEITEN CHARACTER VARYING (100),
     IMM_STRASSE CHARACTER VARYING (100) NOT NULL,
     IMM_ANZAHL INTEGER NOT NULL,
     IMM_ERGARNZUNG CHARACTER VARYING (100),
     IMM_MAK_CNPJ CHARACTER VARYING (50) NOT NULL,
     IMM_STL_ID INTEGER NOT NULL
    ) 
;

ALTER TABLE IMMOBILIE 
    ADD CONSTRAINT IMMOBILIE_PK PRIMARY KEY ( IMM_ID ) ;

ALTER TABLE IMMOBILIE 
    ADD CONSTRAINT IMM_MAKLERBUERO_FK FOREIGN KEY 
    ( 
     IMM_MAK_CNPJ
    ) 
    REFERENCES MAKLERBUERO  
    ( 
     MAK_CNPJ
    ) 
;

CREATE TABLE STADTTEIL 
    ( 
     STL_ID SERIAL,
     STL_NAME CHARACTER VARYING (100) NOT NULL, 
     STL_STT_ID INTEGER NOT NULL
    ) 
;

ALTER TABLE STADTTEIL 
    ADD CONSTRAINT STADTTEIL_PK PRIMARY KEY ( STL_ID ) ;

CREATE TABLE STADT 
    ( 
     STT_ID SERIAL,
     STT_NAME CHARACTER VARYING (100) NOT NULL, 
     STT_BUN_ID INTEGER NOT NULL
    ) 
;

ALTER TABLE STADT 
    ADD CONSTRAINT STADT_PK PRIMARY KEY ( STT_ID ) ;

CREATE TABLE BUNDESLAND 
    ( 
     BUN_ID SERIAL,
     BUN_NAME CHARACTER VARYING (100) NOT NULL
    ) 
;

ALTER TABLE BUNDESLAND 
    ADD CONSTRAINT BUNDESLAND_PK PRIMARY KEY ( BUN_ID ) ;

CREATE TABLE UMFASST 
    ( 
     UMF_STL_ID INTEGER NOT NULL,
     UMF_MAK_CNPJ CHARACTER VARYING (50) NOT NULL
    ) 
;

ALTER TABLE UMFASST 
    ADD CONSTRAINT UMF_STADTTEIL_FK FOREIGN KEY 
    ( 
     UMF_STL_ID
    ) 
    REFERENCES STADTTEIL  
    ( 
     STL_ID
    ) 
;

ALTER TABLE UMFASST 
    ADD CONSTRAINT UMF_IMMOBILIE_FK FOREIGN KEY 
    ( 
     UMF_MAK_CNPJ
    ) 
    REFERENCES MAKLERBUERO  
    ( 
     MAK_CNPJ
    ) 
;

ALTER TABLE FOTO 
    ADD CONSTRAINT FTO_IMMOBILIE_FK FOREIGN KEY 
    ( 
     FTO_IMM_ID
    ) 
    REFERENCES IMMOBILIE  
    ( 
     IMM_ID
    ) 
;

ALTER TABLE MAKLERBUERO 
    ADD CONSTRAINT MAK_STADTTEIL_FK FOREIGN KEY 
    ( 
     MAK_STL_ID
    ) 
    REFERENCES STADTTEIL  
    ( 
     STL_ID
    ) 
;

ALTER TABLE IMMOBILIE 
    ADD CONSTRAINT IMM_STADTTEIL_FK FOREIGN KEY 
    ( 
     IMM_STL_ID
    ) 
    REFERENCES STADTTEIL  
    ( 
     STL_ID
    ) 
;

ALTER TABLE STADTTEIL 
    ADD CONSTRAINT STL_STADT_FK FOREIGN KEY 
    ( 
     STL_STT_ID
    ) 
    REFERENCES STADT  
    ( 
     STT_ID
    ) 
;

ALTER TABLE STADT 
    ADD CONSTRAINT STT_BUNDESLAND_FK FOREIGN KEY 
    ( 
     STT_BUN_ID
    ) 
    REFERENCES BUNDESLAND  
    ( 
     BUN_ID
    ) 
;

--Inserts nas tabelas
INSERT INTO BUNDESLAND (BUN_NAME) VALUES ('Ceara');

INSERT INTO STADT (STT_NAME, STT_BUN_ID) VALUES ('Fortaleza', (select BUN_ID from BUNDESLAND where BUN_NAME='Ceara'));
INSERT INTO STADT (STT_NAME, STT_BUN_ID) VALUES ('Aquiraz', (select BUN_ID from BUNDESLAND where BUN_NAME='Ceara'));
INSERT INTO STADT (STT_NAME, STT_BUN_ID) VALUES ('Eusebio', (select BUN_ID from BUNDESLAND where BUN_NAME='Ceara'));

INSERT INTO STADTTEIL (STL_NAME, STL_STT_ID) VALUES ('Aldeota', (select STT_ID from STADT where STT_NAME='Fortaleza'));
INSERT INTO STADTTEIL (STL_NAME, STL_STT_ID) VALUES ('Meireles', (select STT_ID from STADT where STT_NAME='Fortaleza'));
INSERT INTO STADTTEIL (STL_NAME, STL_STT_ID) VALUES ('Praia de Iracema', (select STT_ID from STADT where STT_NAME='Fortaleza'));
INSERT INTO STADTTEIL (STL_NAME, STL_STT_ID) VALUES ('Porto das Dunas', (select STT_ID from STADT where STT_NAME='Aquiraz'));
INSERT INTO STADTTEIL (STL_NAME, STL_STT_ID) VALUES ('Coite', (select STT_ID from STADT where STT_NAME='Eusebio'));

INSERT INTO MAKLERBUERO (MAK_CNPJ, MAK_NAME, MAK_TELEFONNUMMER1, MAK_STRASSE, MAK_ANZAHL, MAK_ERGARNZUNG, MAK_STL_ID) VALUES ('03.847.655/0001-98', 'Imobiliaria Berlim', '(85) 2273-0135', 'Av Beira Mar', 445, 'Loja 6', (select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Praia de Iracema' and STT_NAME='Fortaleza'));

INSERT INTO UMFASST (UMF_STL_ID, UMF_MAK_CNPJ) VALUES ((select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Aldeota' and STT_NAME='Fortaleza'), (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'));
INSERT INTO UMFASST (UMF_STL_ID, UMF_MAK_CNPJ) VALUES ((select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Meireles' and STT_NAME='Fortaleza'), (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'));
INSERT INTO UMFASST (UMF_STL_ID, UMF_MAK_CNPJ) VALUES ((select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Praia de Iracema' and STT_NAME='Fortaleza'), (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'));
INSERT INTO UMFASST (UMF_STL_ID, UMF_MAK_CNPJ) VALUES ((select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Porto das Dunas' and STT_NAME='Aquiraz'), (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'));
INSERT INTO UMFASST (UMF_STL_ID, UMF_MAK_CNPJ) VALUES ((select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Coite' and STT_NAME='Eusebio'), (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'));

INSERT INTO IMMOBILIE (IMM_PREIS, IMM_FLAECHE, IMM_ZIMMERQUANTITAET, IMM_EGR_PARKPLATZ, IMM_SONNENSTUNDEN, IMM_STRASSE, IMM_ANZAHL, IMM_ERGARNZUNG, IMM_MAK_CNPJ, IMM_STL_ID) VALUES (1500000.00, '400m2', 4, true, 'Manha', 'Avenida Padre Antonio Tomas', 90, 'AP18000', (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'), (select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Aldeota' and STT_NAME='Fortaleza'));
INSERT INTO IMMOBILIE (IMM_PREIS, IMM_FLAECHE, IMM_ZIMMERQUANTITAET, IMM_EGR_PARKPLATZ, IMM_SONNENSTUNDEN, IMM_STRASSE, IMM_ANZAHL, IMM_ERGARNZUNG, IMM_MAK_CNPJ, IMM_STL_ID) VALUES (950000.00, '250m2', 2, true, 'Manha', 'Rua Dep Moreira Rocha', 1903, 'AP402', (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'), (select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Meireles' and STT_NAME='Fortaleza'));
INSERT INTO IMMOBILIE (IMM_PREIS, IMM_FLAECHE, IMM_ZIMMERQUANTITAET, IMM_EGR_PARKPLATZ, IMM_SONNENSTUNDEN, IMM_STRASSE, IMM_ANZAHL, IMM_ERGARNZUNG, IMM_MAK_CNPJ, IMM_STL_ID) VALUES (2000000.00, '190m2', 2, true, 'Manha', 'Av Beira Mar', 1387, 'AP1203', (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'), (select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Praia de Iracema' and STT_NAME='Fortaleza'));
INSERT INTO IMMOBILIE (IMM_PREIS, IMM_FLAECHE, IMM_ZIMMERQUANTITAET, IMM_EGR_PARKPLATZ, IMM_SONNENSTUNDEN, IMM_STRASSE, IMM_ANZAHL, IMM_ERGARNZUNG, IMM_MAK_CNPJ, IMM_STL_ID) VALUES (700000.00, '90m2', 1, true, 'Manha', 'Av dos Golfinhos', 200, 'BL2 AP303', (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'), (select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Porto das Dunas' and STT_NAME='Aquiraz'));
INSERT INTO IMMOBILIE (IMM_PREIS, IMM_FLAECHE, IMM_ZIMMERQUANTITAET, IMM_EGR_PARKPLATZ, IMM_SONNENSTUNDEN, IMM_STRASSE, IMM_ANZAHL, IMM_ERGARNZUNG, IMM_MAK_CNPJ, IMM_STL_ID) VALUES (190000.00, '100m2', 2, true, 'Tarde', 'Estrada Jaboti', 889, 'Casa 1', (select MAK_CNPJ from MAKLERBUERO where MAK_CNPJ='03.847.655/0001-98'), (select STL_ID from STADTTEIL inner join STADT on STL_STT_ID=STT_ID where STL_NAME='Coite' and STT_NAME='Eusebio'));