--Remoção das tabelas
DROP TABLE PHOTO CASCADE;
DROP TABLE IMMOBILE CASCADE;
DROP TABLE AGENCY CASCADE;
DROP TABLE SCOPE CASCADE;
DROP TABLE DISTRICT CASCADE;
DROP TABLE CITY CASCADE;
DROP TABLE STATE CASCADE;

--Criação das tabelas
CREATE TABLE PHOTO 
    ( 
     PHO_IMAGE CHARACTER VARYING (50) NOT NULL,
     PHO_NAME CHARACTER VARYING (100) NOT NULL, 
     PHO_IMM_ID INTEGER NOT NULL
    ) 
;

CREATE TABLE AGENCY 
    ( 
     AGE_CNPJ CHARACTER VARYING (50) NOT NULL,
     AGE_NAME CHARACTER VARYING (100) NOT NULL,
     AGE_PHONE1 CHARACTER VARYING (50),
     AGE_PHONE2 CHARACTER VARYING (50),
     AGE_PHONE3 CHARACTER VARYING (50),
     AGE_STREET CHARACTER VARYING (100),
     AGE_NUMBER INTEGER,
     AGE_COMPLEMENT CHARACTER VARYING (100),
     AGE_DIS_ID INTEGER
    ) 
;

ALTER TABLE AGENCY 
    ADD CONSTRAINT AGENCY_PK PRIMARY KEY ( AGE_CNPJ ) ;

CREATE TABLE IMMOBILE 
    ( 
     IMM_ID SERIAL,
     IMM_PRICE DOUBLE PRECISION NOT NULL,
     IMM_AREA CHARACTER VARYING (50) NOT NULL,
     IMM_NUM_ROOMS INTEGER NOT NULL,
     IMM_PRK_SPACE BOOLEAN NOT NULL,
     IMM_SUN_HOUR CHARACTER VARYING (20) NOT NULL,
     IMM_OTR_DETAILS CHARACTER VARYING (100),
     IMM_STREET CHARACTER VARYING (100) NOT NULL,
     IMM_NUMBER INTEGER NOT NULL,
     IMM_COMPLEMENT CHARACTER VARYING (100),
     IMM_AGE_CNPJ CHARACTER VARYING (50) NOT NULL,
     IMM_DIS_ID INTEGER NOT NULL
    ) 
;

ALTER TABLE IMMOBILE 
    ADD CONSTRAINT IMMOBILE_PK PRIMARY KEY ( IMM_ID ) ;

ALTER TABLE IMMOBILE 
    ADD CONSTRAINT IMM_AGENCY_FK FOREIGN KEY 
    ( 
     IMM_AGE_CNPJ
    ) 
    REFERENCES AGENCY  
    ( 
     AGE_CNPJ
    ) 
;

CREATE TABLE DISTRICT 
    ( 
     DIS_ID SERIAL,
     DIS_NAME CHARACTER VARYING (100) NOT NULL, 
     DIS_CIT_ID INTEGER NOT NULL
    ) 
;

ALTER TABLE DISTRICT 
    ADD CONSTRAINT DISTRICT_PK PRIMARY KEY ( DIS_ID ) ;

CREATE TABLE CITY 
    ( 
     CIT_ID SERIAL,
     CIT_NAME CHARACTER VARYING (100) NOT NULL, 
     CIT_STA_ID INTEGER NOT NULL
    ) 
;

ALTER TABLE CITY 
    ADD CONSTRAINT CITY_PK PRIMARY KEY ( CIT_ID ) ;

CREATE TABLE STATE 
    ( 
     STA_ID SERIAL,
     STA_NAME CHARACTER VARYING (100) NOT NULL
    ) 
;

ALTER TABLE STATE 
    ADD CONSTRAINT STATE_PK PRIMARY KEY ( STA_ID ) ;

CREATE TABLE SCOPE 
    ( 
     SCO_DIS_ID INTEGER NOT NULL,
     SCO_AGE_CNPJ CHARACTER VARYING (50) NOT NULL
    ) 
;

ALTER TABLE SCOPE 
    ADD CONSTRAINT SCO_DISTRICT_FK FOREIGN KEY 
    ( 
     SCO_DIS_ID
    ) 
    REFERENCES DISTRICT  
    ( 
     DIS_ID
    ) 
;

ALTER TABLE SCOPE 
    ADD CONSTRAINT SCO_AGENCY_FK FOREIGN KEY 
    ( 
     SCO_AGE_CNPJ
    ) 
    REFERENCES AGENCY  
    ( 
     AGE_CNPJ
    ) 
;

ALTER TABLE PHOTO 
    ADD CONSTRAINT PHO_IMMOBILE_FK FOREIGN KEY 
    ( 
     PHO_IMM_ID
    ) 
    REFERENCES IMMOBILE  
    ( 
     IMM_ID
    ) 
;

ALTER TABLE AGENCY 
    ADD CONSTRAINT AGE_DISTRICT_FK FOREIGN KEY 
    ( 
     AGE_DIS_ID
    ) 
    REFERENCES DISTRICT  
    ( 
     DIS_ID
    ) 
;

ALTER TABLE IMMOBILE 
    ADD CONSTRAINT IMM_DISTRICT_FK FOREIGN KEY 
    ( 
     IMM_DIS_ID
    ) 
    REFERENCES DISTRICT  
    ( 
     DIS_ID
    ) 
;

ALTER TABLE DISTRICT 
    ADD CONSTRAINT DIS_CITY_FK FOREIGN KEY 
    ( 
     DIS_CIT_ID
    ) 
    REFERENCES CITY  
    ( 
     CIT_ID
    ) 
;

ALTER TABLE CITY 
    ADD CONSTRAINT CIT_STATE_FK FOREIGN KEY 
    ( 
     CIT_STA_ID
    ) 
    REFERENCES STATE  
    ( 
     STA_ID
    ) 
;

--Inserts nas tabelas
INSERT INTO STATE (STA_NAME) VALUES ('Sao Paulo');

INSERT INTO CITY (CIT_NAME, CIT_STA_ID) VALUES ('Sao Paulo', (select STA_ID from STATE where STA_NAME='Sao Paulo'));
INSERT INTO CITY (CIT_NAME, CIT_STA_ID) VALUES ('Guarulhos', (select STA_ID from STATE where STA_NAME='Sao Paulo'));
INSERT INTO CITY (CIT_NAME, CIT_STA_ID) VALUES ('Praia Grande', (select STA_ID from STATE where STA_NAME='Sao Paulo'));

INSERT INTO DISTRICT (DIS_NAME, DIS_CIT_ID) VALUES ('Jardim Paulista', (select CIT_ID from CITY where CIT_NAME='Sao Paulo'));
INSERT INTO DISTRICT (DIS_NAME, DIS_CIT_ID) VALUES ('Campo Belo', (select CIT_ID from CITY where CIT_NAME='Sao Paulo'));
INSERT INTO DISTRICT (DIS_NAME, DIS_CIT_ID) VALUES ('Bom Retiro', (select CIT_ID from CITY where CIT_NAME='Sao Paulo'));
INSERT INTO DISTRICT (DIS_NAME, DIS_CIT_ID) VALUES ('Jardim Paraventi', (select CIT_ID from CITY where CIT_NAME='Guarulhos'));
INSERT INTO DISTRICT (DIS_NAME, DIS_CIT_ID) VALUES ('Vila Tupi', (select CIT_ID from CITY where CIT_NAME='Praia Grande'));

INSERT INTO AGENCY (AGE_CNPJ, AGE_NAME, AGE_PHONE1, AGE_STREET, AGE_NUMBER, AGE_COMPLEMENT, AGE_DIS_ID) VALUES ('14.218.835/0001-27', 'Imobiliaria Londres', '(11) 3033-4878', 'Av Angelica', 475, 'Loja 7', (select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Bom Retiro' and CIT_NAME='Sao Paulo'));

INSERT INTO SCOPE (SCO_DIS_ID, SCO_AGE_CNPJ) VALUES ((select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Jardim Paulista' and CIT_NAME='Sao Paulo'), (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'));
INSERT INTO SCOPE (SCO_DIS_ID, SCO_AGE_CNPJ) VALUES ((select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Campo Belo' and CIT_NAME='Sao Paulo'), (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'));
INSERT INTO SCOPE (SCO_DIS_ID, SCO_AGE_CNPJ) VALUES ((select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Bom Retiro' and CIT_NAME='Sao Paulo'), (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'));
INSERT INTO SCOPE (SCO_DIS_ID, SCO_AGE_CNPJ) VALUES ((select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Jardim Paraventi' and CIT_NAME='Guarulhos'), (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'));
INSERT INTO SCOPE (SCO_DIS_ID, SCO_AGE_CNPJ) VALUES ((select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Vila Tupi' and CIT_NAME='Praia Grande'), (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'));

INSERT INTO IMMOBILE (IMM_PRICE, IMM_AREA, IMM_NUM_ROOMS, IMM_PRK_SPACE, IMM_SUN_HOUR, IMM_STREET, IMM_NUMBER, IMM_COMPLEMENT, IMM_AGE_CNPJ, IMM_DIS_ID) VALUES (960000.00, '150m2', 3, true, 'Manha', 'Alameda Itu', 546, 'BL2 AP1002', (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'), (select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Jardim Paulista' and CIT_NAME='Sao Paulo'));
INSERT INTO IMMOBILE (IMM_PRICE, IMM_AREA, IMM_NUM_ROOMS, IMM_PRK_SPACE, IMM_SUN_HOUR, IMM_STREET, IMM_NUMBER, IMM_COMPLEMENT, IMM_AGE_CNPJ, IMM_DIS_ID) VALUES (425000.00, '70m2', 1, false, 'Tarde', 'Rua Doutor Jesuino Maciel', 1063, 'BL8 AP115', (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'), (select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Campo Belo' and CIT_NAME='Sao Paulo'));
INSERT INTO IMMOBILE (IMM_PRICE, IMM_AREA, IMM_NUM_ROOMS, IMM_PRK_SPACE, IMM_SUN_HOUR, IMM_STREET, IMM_NUMBER, IMM_COMPLEMENT, IMM_AGE_CNPJ, IMM_DIS_ID) VALUES (990000.00, '350m2', 4, true, 'Manha', 'Rua Apa', 366, 'Casa', (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'), (select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Bom Retiro' and CIT_NAME='Sao Paulo'));
INSERT INTO IMMOBILE (IMM_PRICE, IMM_AREA, IMM_NUM_ROOMS, IMM_PRK_SPACE, IMM_SUN_HOUR, IMM_STREET, IMM_NUMBER, IMM_COMPLEMENT, IMM_AGE_CNPJ, IMM_DIS_ID) VALUES (1200000.00, '250m2', 2, true, 'Manha', 'Rua Sousa', 366, 'BL1 AP1402', (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'), (select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Jardim Paraventi' and CIT_NAME='Guarulhos'));
INSERT INTO IMMOBILE (IMM_PRICE, IMM_AREA, IMM_NUM_ROOMS, IMM_PRK_SPACE, IMM_SUN_HOUR, IMM_STREET, IMM_NUMBER, IMM_COMPLEMENT, IMM_AGE_CNPJ, IMM_DIS_ID) VALUES (730000.00, '106m2', 2, true, 'Tarde', 'Rua Tamoios', 3796, 'Casa', (select AGE_CNPJ from AGENCY where AGE_CNPJ='14.218.835/0001-27'), (select DIS_ID from DISTRICT inner join CITY on DIS_CIT_ID=CIT_ID where DIS_NAME='Vila Tupi' and CIT_NAME='Praia Grande'));